# bash_profile

if [ -f .bashrc ]; then
	. .bashrc
fi

export LC_ALL=zh_CN.UTF-8
export XIM=fcitx
export XIM_PROGRAM=fcitx
export XMODIFIERS=@im=fcitx
export GTK_IM_MODULE=XIM
#export QT_IM_MODULE=XIM

