# bash_profile

if [ -f .bashrc ]; then
	. .bashrc
fi

export LC_ALL=zh_CN.UTF-8
#export XIM=scim
#export XIM_PROGRAM=scim
export XMODIFIERS=@im=SCIM    #case matters for this variable!
export GTK_IM_MODULE=scim
export QT_IM_MODULE=scim

export PATH=$PATH:/home/grissiom/bin

export LS_OPTIONS=$LS_OPTIONS' -h'

export LESS=$LESS' -R '

export VISUAL=vim

export GDFONTPATH="/usr/share/fonts/TTF/"
export GNUPLOT_DEFAULT_FONT="wqy-zenhei.ttf"

export CDPATH=".:~:/usr/local/src/My_projects"

# Append any additional sh scripts found in ~/.profile.d
for profile_script in ./.profile.d/*.sh ; do
  if [ -x $profile_script ]; then
    . $profile_script
  fi
done
unset profile_script
