" vim: fdm=marker:
set nocompatible

filetype on
filetype indent on
filetype plugin on
syntax on

" Editing and Encoding {{{
set smarttab
set softtabstop=8
set autoindent

if has('win32') || has('win64') || has('win32unix')
	set encoding=cp936
else
	set encoding=utf-8
endif
" http://blog.sina.com.cn/s/blog_5562534d0100000j.html
" text not garbled with this option ;D
set fileencodings=utf-8,gb18030,utf-16,big5
"}}}

" UI setup {{{
" ========
set showcmd
set showmode
" always show tab line
set showtabline=2

set listchars=tab:>\ 
"set list

set nu
set foldcolumn=2

set ruler
set rulerformat=%m\ %2c,%2v\ \ \ \ %p%%

" always show status line
set laststatus=2
" right part of the status line.
set statusline=%#Error#%m%r%#Normal#
" left part of the status line.
set statusline+=%=
" show the cursor position.
set statusline+=%#Comment#%-14.(%l,%2v%)\ %P
"hi! User1  ctermfg=red

" 貌似即使是全角的双引号在 vim 里始终是当做一个英文字母宽度显示的，所以在这里
" 设置成 double 反而会出问题…
set ambiwidth=single

if has('gui_running')
	colorscheme dark_light256
elseif &term =~ 'xterm'
	set t_Co=256
	colorscheme dark_light256
endif
if has('win32') || has('win64') || has('win32unix')
	set guifont=Consolas:h15:cDEFAULT
endif

"colorscheme inkpot
"colorscheme miko
"set background=dark
"}}}

" Mapping {{{
" =======
imap <F5> <ESC>:w<CR>a
nmap <F5> :w<CR>

nmap <F2> :setlocal spell spelllang=en<CR>
nmap <F3> :setlocal nospell<CR>

nmap <C-Right> gt
nmap <C-Left> gT
imap <C-Right> <ESC>gta
imap <C-Left> <ESC>gTa

" make cs to clean up search
nmap cs :let @/=""<CR>

" press <F4> to start a menu
source $VIMRUNTIME/menu.vim
set wildmenu
set cpo-=<
set wcm=<C-Z>
map <F4> :emenu <C-Z>

map <Up> gk
map <Down> gj

inoremap , ,<Space>
"}}}

" Folding {{{
" =======
" Enable folding, but by default make it act like folding is off, because
" folding is annoying in anything but a few rare cases

set foldenable " Turn on folding
"set foldlevel=100 " Don't autofold anything (but I can still fold manually)
set foldopen-=search " don't open folds when you search into them
set foldopen-=undo " don't open folds when you undo stuff
"}}}

" Local Variables {{{
" ===============
" add po translate info, used by the po.vim script:
let g:po_translator = 'Grissiom <chaos.proton@gmail.com>'
let g:po_lang_team  = 'zh_CN <kde-china@kde.org>'
let g:po_msgfmt_args = '-cvv --check-accelerators=\&'

" Tag list configurations:
" http://vim-taglist.sourceforge.net
"let Tlist_Auto_Open = 1
let Tlist_Exit_OnlyWindow = 1
let Tlist_Auto_Highlight_Tag = 1
let Tlist_Process_File_Always = 1
"}}}

" Misc {{{
" Hold Shift when you want to copy/paste with X.
set mouse=a

" make Chinese text format available
set formatoptions+=mM

set smartcase

set backupskip+=',/etc/rc.d/*,'

" Show trailing whitespace and spaces before tabs
hi link localWhitespaceError Error
au Syntax * syn match localWhitespaceError /\(\zs\%#\|\s\)\+$/ display
au Syntax * syn match localWhitespaceError / \+\ze\t/ display
"}}}

" // The switch of the Source Explorer
nmap <F8> :SrcExplToggle<CR>

" // Set the height of Source Explorer window
let g:SrcExpl_winHeight = 8

" // Set 100 ms for refreshing the Source Explorer
let g:SrcExpl_refreshTime = 100

" // Set "Enter" key to jump into the exact definition context
let g:SrcExpl_jumpKey = "<ENTER>"

" // Set "Space" key for back from the definition context
let g:SrcExpl_gobackKey = "<SPACE>"

" // In order to Avoid conflicts, the Source Explorer should know what plugins
" // are using buffers. And you need add their bufname into the list below
" // according to the command ":buffers!"
let g:SrcExpl_pluginList = [
        \ "__Tag_List__",
        \ "_NERD_tree_",
        \ "Source_Explorer"
    \ ]
" // Enable/Disable the local definition searching, and note that this is not
" // guaranteed to work, the Source Explorer doesn't check the syntax for now.
" // It only searches for a match with the keyword according to command 'gd'
let g:SrcExpl_searchLocalDef = 1

" // Let the Source Explorer update the tags file when opening
let g:SrcExpl_isUpdateTags = 1

" // Use program 'ctags' with argument '--sort=foldcase -R' to create or
" // update a tags file
let g:SrcExpl_updateTagsCmd = "ctags --sort=foldcase -R ."

" // Set "<F12>" key for updating the tags file artificially
let g:SrcExpl_updateTagsKey = "<F12>"

" Open and close all the three plugins on the same time 
nmap <F8>   :TrinityToggleAll<CR>

" Open and close the srcexpl.vim separately 
nmap <F9>   :TrinityToggleSourceExplorer<CR>

" Open and close the taglist.vim separately 
nmap <F10>  :TrinityToggleTagList<CR>

" Open and close the NERD_tree.vim separately 
nmap <F11>  :TrinityToggleNERDTree<CR>
