set nocompatible

filetype on
filetype indent on
filetype plugin on

syntax on

set smarttab
set softtabstop=8
set autoindent
set ruler
set showcmd
set showmode
set listchars=tab:>-,trail:-
set nu
set foldcolumn=2
set statusline+=%f
colorscheme elflord2

" provide middlebutton drag copy and paste
" but thus the mouse could not trigger visual mode
set mouse=r

"set background=dark
set encoding=utf-8
" http://blog.sina.com.cn/s/blog_5562534d0100000j.html
" text not garbled with this option ;D
set fileencodings=utf-8,gb18030,utf-16,big5

" make Chinese text format available
set formatoptions+=mM

" make ESC closer to the finger ;)
imap <F5> <ESC>
nmap <F5> <ESC>

" make xx act as x in input mode
"imap jj <ESC>ja
"imap kk <ESC>ka
"imap ll <ESC>la
"imap hh <ESC>ha

" make <C-C> to clean up search
nmap <C-C> :let @/=""<CR>

" press <F4> to start a menu
source $VIMRUNTIME/menu.vim
set wildmenu
set cpo-=<
set wcm=<C-Z>
map <F4> :emenu <C-Z>

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Folding
"
" Enable folding, but by default make it act like folding is off, because
" folding is annoying in anything but a few rare cases
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set foldenable " Turn on folding
"set foldlevel=100 " Don't autofold anything (but I can still fold manually)
set foldopen-=search " don't open folds when you search into them
set foldopen-=undo " don't open folds when you undo stuff

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" auto close pairs
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
:inoremap , ,<Space>
:inoremap ( ()<ESC>i
:inoremap ) <c-r>=ClosePair(')')<CR>
:inoremap { {}<ESC>i
:inoremap } <c-r>=ClosePair('}')<CR>
:inoremap [ []<ESC>i
:inoremap ] <c-r>=ClosePair(']')<CR>

function ClosePair(char)
	if getline('.')[col('.') - 1] == a:char
		return "\<Right>"
	else
		return a:char
	endif
endf

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" add po translate info, used by the po.vim script:
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let g:po_translator = 'Grissiom <chaos.proton@gmail.com>'
let g:po_lang_team  = 'zh_CN <kde-china@kde.org>'
let g:po_msgfmt_args = '-cvv --check-accelerators=\&'
