" vim: fdm=marker:
set nocompatible

filetype on
filetype indent on
filetype plugin on
syntax on

" Editing and Encoding {{{
set smarttab
set softtabstop=8
set autoindent

set encoding=utf-8
" http://blog.sina.com.cn/s/blog_5562534d0100000j.html
" text not garbled with this option ;D
set fileencodings=utf-8,gb18030,utf-16,big5
"}}}

" UI setup {{{
" ========
set showcmd
set showmode
set listchars=tab:>\ 
"set list
set nu
set foldcolumn=2

set ruler
set rulerformat=%m\ %2c,%2v\ \ \ \ %p%%

" after add %=%([%{Tlist_Get_Tagname_By_Line()}]%) we don't need taglist be
" open on startup.
set statusline=%#Constant#%<%f\ %#Error#%m%r%#Function#\ \ %([%{Tlist_Get_Tagname_By_Line()}]%)%=%#Comment#%-14.(%l,%2v%)\ %P
hi! User1  ctermfg=red
set laststatus=2

" ambiwidth 默认值为 single。在其值为 single 时，若 encoding 为 utf-8，vim显示
" 全角符号时就会出问题，会当作半角显示。
set ambiwidth=double

set t_Co=256
colorscheme dark_light256
"colorscheme miko
"set background=dark
"}}}

" Mapping {{{
" =======

imap <F5> <ESC>:w<CR>a
nmap <F5> :w<CR>

nmap <F2> :setlocal spell spelllang=en<CR>
nmap <F3> :setlocal nospell<CR>

nmap <C-Right> gt
nmap <C-Left> gT
imap <C-Right> <ESC>gta
imap <C-Left> <ESC>gTa

" make cs to clean up search
nmap cs :let @/=""<CR>

" press <F4> to start a menu
source $VIMRUNTIME/menu.vim
set wildmenu
set cpo-=<
set wcm=<C-Z>
map <F4> :emenu <C-Z>

map <Up> gk
map <Down> gj
"}}}

" Folding {{{
" =======
" Enable folding, but by default make it act like folding is off, because
" folding is annoying in anything but a few rare cases

set foldenable " Turn on folding
"set foldlevel=100 " Don't autofold anything (but I can still fold manually)
set foldopen-=search " don't open folds when you search into them
set foldopen-=undo " don't open folds when you undo stuff

" auto close pairs
" ----------------

:inoremap , ,<Space>
:inoremap ( ()<ESC>i
:inoremap ) <c-r>=ClosePair(')')<CR>
:inoremap { {}<ESC>i
:inoremap } <c-r>=ClosePair('}')<CR>
:inoremap [ []<ESC>i
:inoremap ] <c-r>=ClosePair(']')<CR>

function ClosePair(char)
	if getline('.')[col('.') - 1] == a:char
		return "\<Right>"
	else
		return a:char
	endif
endf
"}}}

" Local Variables {{{
" ===============
" add po translate info, used by the po.vim script:
let g:po_translator = 'Grissiom <chaos.proton@gmail.com>'
let g:po_lang_team  = 'zh_CN <kde-china@kde.org>'
let g:po_msgfmt_args = '-cvv --check-accelerators=\&'

" Tag list configurations:
" http://vim-taglist.sourceforge.net
"let Tlist_Auto_Open = 1
let Tlist_Exit_OnlyWindow = 1
let Tlist_Auto_Highlight_Tag = 1
let Tlist_Process_File_Always = 1
"}}}

" Misc {{{
" provide middle button drag copy and paste
" but thus the mouse could not trigger visual mode
set mouse=r

" make Chinese text format available
set formatoptions+=mM

set smartcase

set backupskip+=',/etc/rc.d/*,'

" Show trailing whitespace and spaces before tabs
hi link localWhitespaceError Error
au Syntax * syn match localWhitespaceError /\(\zs\%#\|\s\)\+$/ display
au Syntax * syn match localWhitespaceError / \+\ze\t/ display
"}}}

