#!/bin/zsh
# file name: pkgrep

packages_path='/var/log/packages'
ls='/bin/ls'

cd ${packages_path} 2>/dev/null || echo ${packages_path}' not accessible' || exit 1
grep --color=auto --with-filename $@ *

#echo
#echo 'in script:'
#echo
#(cd /var/log/scripts && grep --color=tty $@ *)
