#!/bin/zsh
# file name: pkgrep

packages_path='/var/log/packages'
ls='/bin/ls'

if [[ -t 1 ]]; then
	color='always'
	out_put_terminal=1
else
	color='never'
	out_put_terminal=0
fi

cd ${packages_path} 2>/dev/null || {echo ${packages_path}' not accessible'; exit 1}
grep --color=$color --with-filename $@ *

#echo
#echo 'in script:'
#echo
#(cd /var/log/scripts && grep --color=tty $@ *)
