#!/bin/sh

packages_path='/var/log/packages'

(cd ${packages_path} 2>/dev/null || echo ${packages_path}' not accessible' || exit 1
grep --color=always $@ *)

#echo
#echo 'in script:'
#echo
#(cd /var/log/scripts && grep --color=tty $@ *)
