#!/bin/zsh
# file name: pkgview

usage="Usage: pkgview [options] <exp>
view the info and content of package matching pattern <exp>

pkgview use grep to filter the names and view(part of vim) for viewing the info
so you don't have write permittion to the files. See man grep for more info
about options and expressions."

[[ $ARGC -eq 0 || $1 == '--help' ]] && {echo $usage; exit 2}

packages_path='/var/log/packages'
ls='/bin/ls'

cd ${packages_path} 2>/dev/null || {echo ${packages_path}' not accessible'; exit 1}

file_names=($($ls | grep --color=auto --no-filename $* - ))
[[ $file_names == '' ]] && {echo 'no package found'; exit 2}
view -c 'set path=/' -p ${file_names}
