#!/bin/sh
# This gives you a Desktop Environment independent way of starting app.
# Only work with runlevel 4 (the graphical XDM/KDM login)

use_scim=0
use_ibus=0
use_fcitx=1
# It seems scim is better then scim-bridge which is used in official settings.
# Overwrite them.
if [ $use_scim -eq 1 ]; then
	export XIM=scim
	export XIM_PROGRAM=scim
	export XMODIFIERS=@im=SCIM    #case matters for this variable!
	export GTK_IM_MODULE=scim
	export QT_IM_MODULE=scim
	scim -d
elif [ $use_ibus -eq 1 ]; then
	export XIM=ibus
	export XIM_PROGRAM="/usr/bin/ibus-daemon"
	export XMODIFIERS="@im=ibus"
	export GTK_IM_MODULE="ibus"
	#it's said that the latest version support qt-immodule, but I haven't try it yet.
	#export QT_IM_MODULE="ibus"
	export QT_IM_MODULE="xim"
	ibus-daemon -rdxt
elif [ $use_fcitx -eq 1 ]; then
	export XIM=fcitx
	export XIM_PROGRAM=/usr/bin/fcitx
	export XMODIFIERS="@im=fcitx"
	export GTK_IM_MODULE=XIM
	export QT_IM_MODULE=XIM
	fcitx -d
fi
